name: NoteCove

options:
  bundleIdPrefix: com.notecove
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 6.29.3

settings:
  MARKETING_VERSION: 0.1.0
  CURRENT_PROJECT_VERSION: 1

targets:
  NoteCove:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: Sources
        createIntermediateGroups: true
        excludes:
          - "**/*.js"

    resources:
      - Sources/Resources/notecove-bridge.js
      - Sources/Resources/tiptap-bundle.js
      - Sources/Resources/editor.html

    preBuildScripts:
      - name: "Build TipTap Bundle"
        basedOnDependencyAnalysis: false
        script: |
          export PATH="$HOME/.nvm/versions/node/v25.0.0/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"
          cd "${PROJECT_DIR}/../shared"
          node scripts/build-editor-bundle.js
      - name: "Copy JS Bundles"
        basedOnDependencyAnalysis: false
        script: |
          cp "${PROJECT_DIR}/Sources/Resources/notecove-bridge.js" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/notecove-bridge.js"
          cp "${PROJECT_DIR}/Sources/Resources/tiptap-bundle.js" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/tiptap-bundle.js"

    info:
      path: Sources/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false

        UILaunchScreen: {}

        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

        CFBundleDisplayName: NoteCove
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)

        # File access for CRDT sync
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true

        # iCloud Drive access
        NSUbiquitousContainers:
          iCloud.com.notecove.NoteCove:
            NSUbiquitousContainerIsDocumentScopePublic: true
            NSUbiquitousContainerName: NoteCove
            NSUbiquitousContainerSupportedFolderLevels: Any

    entitlements:
      path: Sources/NoteCove.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.notecove.NoteCove
        com.apple.developer.icloud-services:
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.notecove.NoteCove

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notecove.NoteCove
        PRODUCT_NAME: NoteCove
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/NoteCove.entitlements
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        ENABLE_PREVIEWS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""  # User will set this
        CODE_SIGN_STYLE: Automatic

      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"

      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SWIFT_COMPILATION_MODE: wholemodule

    dependencies:
      - sdk: JavaScriptCore.framework
      - sdk: Foundation.framework
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: UniformTypeIdentifiers.framework
      - package: GRDB

    scheme:
      testTargets:
        - NoteCoveTests
        - NoteCoveUITests
      gatherCoverageData: true

  NoteCoveTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: Tests
        createIntermediateGroups: true

    dependencies:
      - target: NoteCove
      - package: GRDB

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.notecove.NoteCoveTests
      INFOPLIST_FILE: Tests/Info.plist
      SWIFT_VERSION: "6.0"
      TARGETED_DEVICE_FAMILY: "1,2"

  NoteCoveUITests:
    type: bundle.ui-testing
    platform: iOS

    sources:
      - path: UITests
        createIntermediateGroups: true

    dependencies:
      - target: NoteCove

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.notecove.NoteCoveUITests
      SWIFT_VERSION: "6.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      TEST_TARGET_NAME: NoteCove
      GENERATE_INFOPLIST_FILE: true

schemes:
  NoteCove:
    build:
      targets:
        NoteCove: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - NoteCoveTests
        - NoteCoveUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
