# NoteCove iOS App
#
# To run on a physical device:
# 1. Get your Team ID from Xcode (Preferences > Accounts > Your Team > Team ID)
#    Or find it at https://developer.apple.com/account -> Membership -> Team ID
# 2. Set it below in DEVELOPMENT_TEAM, or set the NC_TEAM_ID environment variable
# 3. Run: xcodegen generate && open NoteCove.xcodeproj
#
# Note: iCloud entitlements require a paid Apple Developer account ($99/year)
# For free accounts, use the simulator instead.

name: NoteCove
options:
  bundleIdPrefix: com.notecove
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    version: 7.0.0

targets:
  NoteCove:
    type: application
    platform: iOS
    sources:
      - path: NoteCove
        excludes:
          - "**/*.entitlements"
      - path: NoteCove/CRDT/Resources/ios-bridge-bundle.js
        type: file
        buildPhase: resources
      - path: NoteCove/Editor/Resources/ios-editor-bundle.js
        type: file
        buildPhase: resources
      - path: NoteCove/Editor/Resources/ios-editor.html
        type: file
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notecove.NoteCove
        PRODUCT_NAME: NoteCove
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: NoteCove/Info.plist
        CODE_SIGN_ENTITLEMENTS: NoteCove/NoteCove.entitlements
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        SWIFT_VERSION: "6.0"
        ENABLE_PREVIEWS: true
    dependencies:
      - package: GRDB
    entitlements:
      path: NoteCove/NoteCove.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.notecove.NoteCove
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.notecove.NoteCove
        com.apple.developer.icloud-services:
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.notecove.NoteCove

  NoteCoveTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NoteCoveTests
      - path: NoteCove/CRDT/Resources/ios-bridge-bundle.js
        type: file
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notecove.NoteCoveTests
        INFOPLIST_FILE: NoteCoveTests/Info.plist
    dependencies:
      - target: NoteCove

  NoteCoveUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: NoteCoveUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notecove.NoteCoveUITests
        INFOPLIST_FILE: NoteCoveUITests/Info.plist
    dependencies:
      - target: NoteCove

schemes:
  NoteCove:
    build:
      targets:
        NoteCove: all
        NoteCoveTests: [test]
        NoteCoveUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - NoteCoveTests
        - NoteCoveUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
